### ISSUE TITLE
'multichannel' argument is deprecated in scikit-image>=0.20

### ISSUE THREAD

**Issue by tnair-c2s** [up42/fake-geo-images#15]
Scikit-image has deprecated the multichannel argument for channel_axis in 0.20 and above. See: https://github.com/scikit-image/scikit-image/issues/4294 for more information.

Could we update the requirements of fake-geo-images to have scikit-image<0.20. Better yet, could we update the usage to keep the package up to date? All it requires is to change the call in [add_img_pattern](https://github.com/up42/fake-geo-images/blob/master/fake_geo_images/fakegeoimages.py#L105) from

```python
fake_geo_images.fakegeoimages.add_img_pattern(..., multichannel=False) 
```
to
```python
fake_geo_images.fakegeoimages.add_img_pattern(..., channel_axis=None) 
```

**Comment by seedlit** [comment]
thanks for pointing out @tnair-c2s  :) 
We will fix it soon

**Comment by seedlit** [comment]
@tnair-c2s we have released a new version fixing this issue - https://pypi.org/project/fake-geo-images/

For future, if you would like to be a contributor, feel free to create a PR :) 
Thanks again for reporting the issue.
